apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lianghua.fullname" . }}-config
  labels:
    {{- include "lianghua.labels" . | nindent 4 }}
data:
  APP_ENV: "production"
  LOG_LEVEL: "INFO"
  PROMETHEUS_MULTIPROC_DIR: "/tmp/prometheus"
  FLOWER_PORT: "5555"
  CELERY_BROKER_URL: "redis://{{ include "lianghua.fullname" . }}-redis-master:6379/0"
  CELERY_RESULT_BACKEND: "redis://{{ include "lianghua.fullname" . }}-redis-master:6379/1"
